### ISSUE TITLE
'status is not defined' with v0.5.0

### ISSUE THREAD

**Issue by janro1** [bobheadxi/deployments#27]
Hi @bobheadxi,

our pipelines are failing with the newest version. I checked the release notes and saw no breaking change there. So I assume it is a bug:

```
Run bobheadxi/deployments@master
  with:
    step: finish
    token: ***
    status: success
    deployment_id: ***
    env_url: https://test.example.com
    no_override: true
  env:
    CI: true
Error: unexpected error encounterd: status is not defined
```

I guess it is because we're trying to access job.status, like this: ```status: ${{ job.status }}```

**Comment by jhheider** [comment]
Confirmed that using `bobheadxi/demployments@v0.4.3` restores functionality.

**Comment by bobheadxi** [comment]
I just cut a release that should fix this: https://github.com/bobheadxi/deployments/releases/tag/v0.5.1 - sorry about that!

**Comment by ascasson** [comment]
Thanks for the fix! It's weird, though. We're pulling `bobheadxi/deployments@master` but still throws same error

**Comment by jhheider** [comment]
I think you're missing the 'v' in the version string.

**Comment by ascasson** [comment]
@jhheider Good catch! Unfortunately that new version appears to still throw the error. `0.4.3` is working.

**Comment by bwdmonkey** [comment]
@bobheadxi related to #28

**Comment by PhilippMeissner** [comment]
Targeting `bobheadxi/deployments@master` causes said error, so does `bobheadxi/deployments@v0.5.1`. Fixed it by temporarily targeting `bobheadxi/deployments@v.0.4.3`.

**Comment by bwdmonkey** [comment]
Closing upon the release of v0.5.2. See #28. Reopen if it still doesn't work 😅

**Comment by PhilippMeissner** [comment]
Yep, seems to work fine now. Maybe you can set up a small dummy-project and trigger a pre-release deployment there to see if it works just fine for the future.

**Comment by bwdmonkey** [comment]
@PhilippMeissner Sounds good. Thanks!
